# Generated by Django 4.0.2 on 2022-02-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='book_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='book_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
