# Generated by Django 4.0.2 on 2022-02-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0005_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
