# Generated by Django 4.0.2 on 2022-02-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider', '0007_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
